### ISSUE TITLE
What version of React Router are you using?

### ISSUE THREAD

**Issue by funnynight** [funnynight/solana-escrow#2]
v6.11.0

Steps to Reproduce
Check this repo https://stackblitz.com/edit/react-ts-ffc4fk?file=App.tsx

Expected Behavior
When I go to dashboard route it should route to /dashboard/profile

Actual Behavior
it is routing to /dashboard/profile/profile

**Comment by BigDreamDev** [comment]
My code earlier.

 <Routes>
  <Route index element={<Navigate to="db" />} />
  <Route path="db" element={<Db/>} />
  </Routes>
Working earlier but now I have to

<Routes>
  <Route index element={<Navigate to="/app/db" />} />
  <Route path="db" element={<Db/>} />
</Routes>

**Comment by funnynight** [comment]
Thx
Really good solution
